name: alice
description: Alice is an HTTP Inspector tool which helps debugging http requests. It catches and stores http requests and responses, which can be viewed via simple UI.
version: 0.3.2
homepage: https://github.com/abdur-rohman/alice_lite

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5
  dio: ^4.0.6
  flutter_local_notifications: ^12.0.3
  rxdart: ^0.27.5

  permission_handler: ^10.2.0
  package_info_plus: ^3.0.1
  share_plus: ^6.1.0
  chopper: ^5.1.0
  collection: ^1.16.0

dev_dependencies:
  lint: ^1.10.0
